language: go

go:
  - 1.5

addons:
  hosts:
    - le.wtf
  apt:
    packages:
      - lsb-release
      - python-dev
      - python-virtualenv
      - gcc
      - libaugeas0
      - libssl-dev
      - libffi-dev
      - ca-certificates
      - rsyslog
  mariadb: "10.0"

sudo: false

services:
  - rabbitmq
  - mysql

matrix:
  fast_finish: true

# Only build pushes to the master branch (and PRs)
branches:
  only:
    - master

before_install:
  # Github-PR-Status secret
  - openssl aes-256-cbc -K $encrypted_53b2630f0fb4_key -iv $encrypted_53b2630f0fb4_iv -in test/github-secret.json.enc -out test/github-secret.json -d || true

  - travis_retry go get golang.org/x/tools/cmd/vet
  - travis_retry go get golang.org/x/tools/cmd/cover
  - travis_retry go get github.com/golang/lint/golint
  - travis_retry go get github.com/mattn/goveralls
  - travis_retry go get github.com/modocache/gover
  - travis_retry go get github.com/jcjones/github-pr-status
  - travis_retry go get bitbucket.org/liamstask/goose/cmd/goose

  # Boulder consists of multiple Go packages, which
  # refer to each other by their absolute GitHub path,
  # e.g. github.com/letsencrypt/boulder/analysis. That means, by default, if
  # someone forks the repo, Travis won't pass on their own repo. To fix that,
  # we add a symlink.
  - mkdir -p $TRAVIS_BUILD_DIR $GOPATH/src/github.com/letsencrypt
  - test ! -d $GOPATH/src/github.com/letsencrypt/boulder && ln -s $TRAVIS_BUILD_DIR $GOPATH/src/github.com/letsencrypt/boulder || true

env:
  global:
    - LETSENCRYPT_PATH=/tmp/letsencrypt
  matrix:
    - SKIP_INTEGRATION_TESTS=1
    - SKIP_UNIT_TESTS=1
    - RUN_MAKE=1 SKIP_UNIT_TESTS=1 SKIP_INTEGRATION_TESTS=1

script:
  - bash test/travis_make.sh
  - bash test.sh
