language: go

go:
  - 1.4.1

matrix:
  fast_finish: true

before_install:
  - go get golang.org/x/tools/cmd/vet
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/golang/lint/golint
  - go get github.com/mattn/goveralls
  - go get github.com/modocache/gover

script:
  - go vet -x ./...
  - $HOME/gopath/bin/golint ./...
  - go test -covermode=count -coverprofile=analysis.coverprofile ./analysis/
  - go test -covermode=count -coverprofile=ca.coverprofile ./ca/
  - go test -covermode=count -coverprofile=core.coverprofile ./core/
  - go test -covermode=count -coverprofile=log.coverprofile ./log/
  - go test -covermode=count -coverprofile=ra.coverprofile ./ra/
  - go test -covermode=count -coverprofile=rpc.coverprofile ./rpc/
  - go test -covermode=count -coverprofile=sa.coverprofile ./sa/
  - go test -covermode=count -coverprofile=test.coverprofile ./test/
  - go test -covermode=count -coverprofile=va.coverprofile ./va/
  - go test -covermode=count -coverprofile=wfe.coverprofile ./wfe/
  - $HOME/gopath/bin/gover
  - $HOME/gopath/bin/goveralls -coverprofile=gover.coverprofile -service=travis-ci
