language: go

go:
  - 1.4.1

services:
  - rabbitmq

sudo: required

matrix:
  fast_finish: true

# Only build pushes to the master branch (and PRs)
branches:
  only:
    - master

sudo: required

before_install:
  # Github-PR-Status secret
  - openssl aes-256-cbc -K $encrypted_53b2630f0fb4_key -iv $encrypted_53b2630f0fb4_iv -in test/github-secret.json.enc -out test/github-secret.json -d || true

  - go get golang.org/x/tools/cmd/vet
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/golang/lint/golint
  - go get github.com/mattn/goveralls
  - go get github.com/modocache/gover
  - go get github.com/jcjones/github-pr-status

  # Boulder consists of multiple Go packages, which
  # refer to each other by their absolute GitHub path,
  # e.g. github.com/letsencrypt/boulder/analysis. That means, by default, if
  # someone forks the repo, Travis won't pass on their own repo. To fix that,
  # we add a symlink.
  - mkdir -p $TRAVIS_BUILD_DIR $GOPATH/src/github.com/letsencrypt
  - test ! -d $GOPATH/src/github.com/letsencrypt/boulder && ln -s $TRAVIS_BUILD_DIR $GOPATH/src/github.com/letsencrypt/boulder || true
  - git clone https://www.github.com/letsencrypt/lets-encrypt-preview.git "$LETSENCRYPT_PATH"
  - cd "$LETSENCRYPT_PATH"
  - sudo ./bootstrap/debian.sh
  - virtualenv --no-site-packages -p python2 ./venv
  - travis_retry ./venv/bin/pip install -r requirements.txt -e .
  - "cd -"

env:
  - LETSENCRYPT_PATH=/tmp/letsencrypt

script:
  - make -j4 # Travis has 2 cores per build instance
  - bash test.sh
