language: go

go:
  - 1.4.1

matrix:
  fast_finish: true

before_install:
  - go get golang.org/x/tools/cmd/vet
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/golang/lint/golint
  - go get github.com/mattn/goveralls
  - go get github.com/modocache/gover

script:
  - go build cmd/activity-monitor/main.go
  - go build cmd/boulder/main.go
  - go build cmd/boulder-ca/main.go
  - go build cmd/boulder-ra/main.go
  - go build cmd/boulder-sa/main.go
  - go build cmd/boulder-va/main.go
  - go build cmd/boulder-wfe/main.go
  - bash test.sh
