language: go

go:
  - 1.4.1

services:
  - rabbitmq

sudo: required

matrix:
  fast_finish: true

before_install:
  - go get golang.org/x/tools/cmd/vet
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/golang/lint/golint
  - go get github.com/mattn/goveralls
  - go get github.com/modocache/gover
  # Boulder consists of multiple Go packages, which
  # refer to each other by their absolute GitHub path,
  # e.g. github.com/letsencrypt/boulder/analysis. That means, by default, if
  # someone forks the repo, Travis won't pass on their own repo. To fix that,
  # we add a symlink.
  - mkdir -p $TRAVIS_BUILD_DIR $GOPATH/src/github.com/letsencrypt
  - test ! -d $GOPATH/src/github.com/letsencrypt/boulder && ln -s $TRAVIS_BUILD_DIR $GOPATH/src/github.com/letsencrypt/boulder || true

script:
  - make -j4 # Travis has 2 cores per build instance
  - bash test.sh
