[application]

name = "boulder"
version = "0.0.1"
authors = ["ISRG <info@letsencrypt.org>"]

# Rewrote dependencies in our source tree using:
# find analysis/ cmd/ core/ jose/ log/ policy/ ra/ rpc/ sa/ test/ va/ wfe/ -name '*.go' | xargs perl -ibak -lpe 's,"(github.com/(?!letsencrypt).*)","github.com/letsencrypt/boulder/vendor/_nuts/$1",'
# TODO: I think nut is supposed to do this for you but it may only apply to
# internal imports within your dependencies.
[dependencies]
# We have to specify a path within cfssl, otherwise we get an error about no
# buildable files. But this fetches the whole repo.
"github.com/cloudflare/cfssl/auth" = "1415724f395ffd7aa29176066765cabc68193453"
"github.com/streadway/amqp" = "150b7f24d6ad507e6026c13d85ce1f1391ac7400"
"github.com/mattn/go-sqlite3" = "308067797b0fcce4ca06362580dc6db77c1bfeda"
"github.com/codegangsta/cli" = "e1712f381785e32046927f64a7c86fe569203196"
