apiVersion: v1
kind: Namespace
metadata:
  name: boulder
  labels:
    name: boulder
    app.kubernetes.io/name: boulder
    app.kubernetes.io/component: namespace
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: boulder-service-account
  namespace: boulder
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: boulder
  name: boulder-role
rules:
- apiGroups: [""]
  resources: ["pods", "services", "endpoints", "configmaps", "secrets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "statefulsets"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: boulder-role-binding
  namespace: boulder
subjects:
- kind: ServiceAccount
  name: boulder-service-account
  namespace: boulder
roleRef:
  kind: Role
  name: boulder-role
  apiGroup: rbac.authorization.k8s.io