apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: boulder-redis-1
  namespace: boulder-test
  labels:
    app: boulder-redis-1
    app.kubernetes.io/name: redis
    app.kubernetes.io/instance: redis-1
    app.kubernetes.io/component: rate-limiting
    app.kubernetes.io/part-of: boulder
    network-segment: internal
    app-type: infrastructure
spec:
  serviceName: boulder-redis-1
  replicas: 1
  selector:
    matchLabels:
      app: boulder-redis-1
  template:
    metadata:
      labels:
        app: boulder-redis-1
        network: internal
        network-segment: internal
        app-type: infrastructure
    spec:
      containers:
      - name: redis
        image: redis:6.2.7
        command:
        - redis-server
        - /etc/redis/redis.conf
        ports:
        - containerPort: 6379
          name: redis
        volumeMounts:
        - name: redis-config
          mountPath: /etc/redis
        - name: redis-data
          mountPath: /data
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        readinessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 3
        livenessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 3
      volumes:
      - name: redis-config
        configMap:
          name: redis-config
  volumeClaimTemplates:
  - metadata:
      name: redis-data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi