apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: bmysql
  namespace: boulder-test
  labels:
    app: bmysql
    app.kubernetes.io/name: mariadb
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: boulder
spec:
  serviceName: bmysql
  replicas: 1
  selector:
    matchLabels:
      app: bmysql
  template:
    metadata:
      labels:
        app: bmysql
        network: internal
    spec:
      containers:
      - name: mariadb
        image: mariadb:10.11.13
        env:
        - name: MYSQL_ALLOW_EMPTY_PASSWORD
          value: "yes"
        args:
        - --bind-address=0.0.0.0
        - --slow-query-log
        - --log-output=TABLE
        - --log-queries-not-using-indexes=ON
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
        - name: mysql-init
          mountPath: /docker-entrypoint-initdb.d
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        readinessProbe:
          exec:
            command:
            - mysqladmin
            - ping
            - -h
            - localhost
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        livenessProbe:
          exec:
            command:
            - mysqladmin
            - ping
            - -h
            - localhost
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
      volumes:
      - name: mysql-init
        configMap:
          name: mysql-init-scripts
          optional: true
  volumeClaimTemplates:
  - metadata:
      name: mysql-data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 10Gi