apiVersion: v1
kind: Service
metadata:
  name: bconsul
  namespace: boulder-test
  labels:
    app: bconsul
    app.kubernetes.io/name: consul
    app.kubernetes.io/component: service-discovery
    app.kubernetes.io/part-of: boulder
spec:
  type: ClusterIP
  clusterIP: None  # Headless service for StatefulSet
  selector:
    app: bconsul
  ports:
  - port: 8500
    targetPort: 8500
    protocol: TCP
    name: http
  - port: 8503
    targetPort: 8503
    protocol: TCP
    name: grpc-tls
  - port: 53
    targetPort: 53
    protocol: TCP
    name: dns-tcp
  - port: 53
    targetPort: 53
    protocol: UDP
    name: dns-udp
---
apiVersion: v1
kind: Service
metadata:
  name: consul-service-consul
  namespace: boulder-test
  labels:
    app: bconsul
    app.kubernetes.io/name: consul
    app.kubernetes.io/component: service-discovery
    app.kubernetes.io/part-of: boulder
spec:
  type: ClusterIP
  selector:
    app: bconsul
  ports:
  - port: 8500
    targetPort: 8500
    protocol: TCP
    name: http