apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: boulder-redis-1
  namespace: boulder
spec:
  template:
    spec:
      containers:
      - name: redis
        command:
        - redis-server
        - /etc/redis/redis.conf
        ports:
        - containerPort: 6379
          name: redis
        readinessProbe:
          exec:
            command:
            - redis-cli
            - ping
        livenessProbe:
          exec:
            command:
            - redis-cli
            - ping
        volumeMounts:
        - name: redis-config
          mountPath: /etc/redis
        - name: redis-data
          mountPath: /data
      volumes:
      - name: redis-config
        configMap:
          name: redis-config
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: boulder-redis-2
  namespace: boulder
spec:
  template:
    spec:
      containers:
      - name: redis
        command:
        - redis-server
        - /etc/redis/redis.conf
        ports:
        - containerPort: 6379
          name: redis
        readinessProbe:
          exec:
            command:
            - redis-cli
            - ping
        livenessProbe:
          exec:
            command:
            - redis-cli
            - ping
        volumeMounts:
        - name: redis-config
          mountPath: /etc/redis
        - name: redis-data
          mountPath: /data
      volumes:
      - name: redis-config
        configMap:
          name: redis-config
---
apiVersion: v1
kind: Service
metadata:
  name: boulder-redis-1
  namespace: boulder
spec:
  ports:
  - port: 6379
    targetPort: 6379
    protocol: TCP
    name: redis
---
apiVersion: v1
kind: Service
metadata:
  name: boulder-redis-2
  namespace: boulder
spec:
  ports:
  - port: 6379
    targetPort: 6379
    protocol: TCP
    name: redis