name: update master branch
on:
  push:
    branches: [ main ]
jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v2
        with:
          script: |
            github.git.updateRef({
              owner: "letsencrypt",
              repo: "boulder",
              ref: "heads/master",
              sha: context.sha,
            })
