apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: boulder-staging

# For staging, start with base and modify
resources:
  - ../../

# Override labels for staging environment
labels:
- includeSelectors: true
  pairs:
    environment: staging
    app.kubernetes.io/profile: staging

# Staging-specific configuration
configMapGenerator:
  - name: boulder-staging-config
    behavior: create
    literals:
      - BOULDER_CONFIG_DIR=test/config  # Initially same as test
      - STAGING_PROFILE=enabled
      # Will evolve through Phases 2-6

# Phase 2: Service splitting patches will go here
# patchesStrategicMerge:
#   - phase2-service-split.yaml

# Phase 3: Kubernetes-native initialization
# - phase3-init-jobs.yaml

# Phase 4: ConfigMaps and Secrets
# configMapGenerator for service-specific configs

# Phase 5: Observability
# - phase5-prometheus.yaml
# - phase5-enhanced-jaeger.yaml

# Phase 6: Production features
# - phase6-hpa.yaml
# - phase6-network-policies.yaml